### PR TITLE
Keep spaces around quoted values

### PR DESCRIPTION
**Pull request by DelusionalLogic**
This should resolve issue #19

### CODE REVIEW

**Comment by touilleMan** [comment]
This is some fine work ;-)

I think this patch would benefit if you add a unittest to underline the expected changes and prevent regression. Can you do this ?

**Comment by DelusionalLogic** [comment]
The current tests don't seem to facilitate this, From what i can tell most of the tests use generated data, this change is in the parser. The tests that actually do load files are just checking if they return null. Since this change doesn't affect what files loads, but how they load, the current methodology wouldn't catch it.

I'd like to know where a test like this (where i have to check specific loaded data from a file) should be placed.

**Comment by touilleMan** [comment]
I've made the unittest that show the bug, can you integrate it to your PR ? (feel free to improve it of course ^^)

```
diff --git a/test/test_iniparser.c b/test/test_iniparser.c
index e207554..5ae34e1 100644
--- a/test/test_iniparser.c
+++ b/test/test_iniparser.c
@@ -498,6 +498,10 @@ void Test_iniparser_line(CuTest *tc)
     CuAssertIntEquals(tc, LINE_COMMENT, iniparser_line(";comment", section, key, val));
     CuAssertIntEquals(tc, LINE_COMMENT, iniparser_line(" # comment", section, key, val));
 
+    CuAssertIntEquals(tc, LINE_VALUE, iniparser_line("key = \"  do_not_strip  \"", section, key, val));
+    CuAssertStrEquals(tc, "key", key);
+    CuAssertStrEquals(tc, "  do_not_strip  ", val);
+
     /* Test syntax error */
     CuAssertIntEquals(tc, LINE_ERROR, iniparser_line("empty_value", section, key, val));
     CuAssertIntEquals(tc, LINE_ERROR, iniparser_line("not finished\\", section, key, val));
```

**Comment by DelusionalLogic** [comment]
That should be apply the patch!

**Comment by touilleMan** [comment]
aaaand merged ! good work :+1:

**Pull request merged**
