### PR TITLE
Add Github Actions CI

### PR DESCRIPTION
**Pull request by hramrach**

### CODE REVIEW

**Comment by lmoellendorf** [comment]
Hi @hramrach !
Thank you for contributing to iniparser and also thank you for your hint in #151.

@ndevilla added me as co-maintainer a few days ago. And after reading through the open issues and merge requests, the first thing I did, was creating [iniparser-meta](https://gitlab.com/iniparser/iniparser-meta) in order to build and test iniparser automatically. And also to provide an upstream standard build environment. I saw that many issues were related to build issues and my hope is to provide means to solve those. 

I chose Gitlab because I am very familiar with it so it is easy for me to maintain.

Maybe have a look at iniparser-meta to see if you could contribute there?

**Comment by hramrach** [comment]
I did not experience those build issues, I can build iniparser on Windows and Linux with the provided makefile as is.

Even though I occasionally work with projects that use CMake I still don't understand it. Given that situation I will stay away from iniparser-meta.

I see you added the valgrind check there, and besides the biolerplate to run the Github CI there is nothing particularly useful here.

My recommendation is to pick a build system and use only one. Dealing with more than one at the same time is just source of additional bugs.

**Comment by lmoellendorf** [comment]
> I did not experience those build issues, I can build iniparser on Windows and Linux with the provided makefile as is.

Ok, but there are issues like #121 and #98 and [patches](https://git.openembedded.org/meta-openembedded/tree/meta-oe/recipes-support/iniparser/iniparser/Add-CMake-support.patch?h=master). I figured there is a demand to integrate iniparser into build systems.  
 
> Even though I occasionally work with projects that use CMake I still don't understand it. Given that situation I will stay away from iniparser-meta.

If there is anything you think is missing just let me know.

> My recommendation is to pick a build system and use only one. Dealing with more than one at the same time is just source of additional bugs.

You are right. First, I thought about integrating CMake directly into iniparser. This is technically less effort. But then I considered that iniparser may have some users loving it for its simplicity. And I think iniparser-meta can solve build and packaging issues as well.

The CI also [runs the Makefile based build](https://gitlab.com/iniparser/iniparser-meta/-/jobs/6146611655) to make sure that it works.

**Comment by hramrach** [comment]
The reality is that different build systems have different strengths and different weaknesses. If you support multiple then the user is free to pick the one that provides the strengths they like but you as the maintainer have to deal with weaknesses of all of them.

That there is a patch to use a different build system or a generic request for 'making some changes' does not mean the current one is insufficient.

A makefile is completely capable of header file installation, generating a .pc file, providing variables for build customization, and using standard tools like pkgconfig to pick up dependencies.

Where it gets dodgy is when OS features need to be detected (eg. if you wanted to detect that the OS has working sscanf implementation).

**Pull request closed without merging**
