### PR TITLE
I think an interface for int64_t is needed.

### PR DESCRIPTION
**Pull request by linghuazaii**
Add an interface `iniparser_getint64(...)`.

### CODE REVIEW

**Comment by touilleMan** [comment]
Thanks for this PR, few remarks:

- this function is pretty similar to `iniparser_getint` so you should reimplement it with a call to your new function
- I would call the function `iniparser_getlongint` to stay consistent with `iniparser_getdouble` and `iniparser_getint`
- can you add some unittests too, it should be pretty similar to this https://github.com/ndevilla/iniparser/blob/master/test/test_iniparser.c#L277

**Comment by linghuazaii** [comment]
@touilleMan Interface for _int64_t_ has been changed to `iniparser_getlongint()`,and unittest for this interface is added.I also added interface for _int64_t_ in CuTest.h/CuTest.c. All tests are passed.Please 
check the latest commit.

**Comment by touilleMan** [comment]
Your tests are fine and you did well to customize cuTest lib for the needs :+1: 

- I saw you still use `int64_t`, given `stdint.h` is not used in this library, you should replace them with `long int` (it is the signature of `strtol` anyway).
- You should reimplement `iniparser_getint` as a call to your new function with a cast

**Comment by linghuazaii** [comment]
@touilleMan Got your point.I am a little insensitive in understanding English.:) Updated,please check.

**Comment by touilleMan** [comment]
Merged, thx :+1:

**Pull request merged**
